title: Oscar Téllez blog
email: oscartzgz@gmail.com
description: >-
  Soy Oscar, ingeniero en sistemas, aficionado a la tecnología, actualmente
  desarrollador web RoR.
baseurl: ''
url: ''
twitter_username: oscartzgz
github_username: oscartzgz
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
